micronaut:
  application:
    name: micronautOktaExample
  security:
    enabled: true
    token:
      jwt:
        enabled: true
        signatures:
          jwks:
            okta:
              url: https://dev-2345032.okta.com/oauth2/default/v1/keys
netty:
  default:
    allocator:
      max-order: 3
